window.esdocSearchIndex = [
  [
    "libhoney/src/builder.js~builder",
    "class/src/builder.js~Builder.html",
    "<span>Builder</span> <span class=\"search-result-import-path\">libhoney/src/builder.js</span>",
    "class"
  ],
  [
    "libhoney/src/event.js~event",
    "class/src/event.js~Event.html",
    "<span>Event</span> <span class=\"search-result-import-path\">libhoney/src/event.js</span>",
    "class"
  ],
  [
    "libhoney/src/libhoney.js~libhoney",
    "class/src/libhoney.js~Libhoney.html",
    "<span>Libhoney</span> <span class=\"search-result-import-path\">libhoney/src/libhoney.js</span>",
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "",
    "test-file/test/libhoney_test.js.html#lineNumber17",
    "libhoney",
    "test"
  ],
  [
    "",
    "test-file/test/builder_test.js.html#lineNumber4",
    "libhoney builder",
    "test"
  ],
  [
    "",
    "test-file/test/builder_test.js.html#lineNumber16",
    "libhoney builder accepts dict-like arguments to .add()",
    "test"
  ],
  [
    "",
    "test-file/test/builder_test.js.html#lineNumber7",
    "libhoney builder takes fields and dynamic fields in ctor",
    "test"
  ],
  [
    "",
    "test-file/test/libhoney_test.js.html#lineNumber18",
    "libhoney constructor options",
    "test"
  ],
  [
    "",
    "test-file/test/libhoney_test.js.html#lineNumber19",
    "libhoney constructor options should be communicated to transmission constructor",
    "test"
  ],
  [
    "",
    "test-file/test/libhoney_test.js.html#lineNumber30",
    "libhoney event properties",
    "test"
  ],
  [
    "",
    "test-file/test/libhoney_test.js.html#lineNumber51",
    "libhoney event properties should come from libhoney options if not specified in event",
    "test"
  ],
  [
    "",
    "test-file/test/libhoney_test.js.html#lineNumber31",
    "libhoney event properties should ultimately fallback to hardcoded defaults",
    "test"
  ],
  [
    "",
    "test-file/test/event_test.js.html#lineNumber4",
    "libhoney events",
    "test"
  ],
  [
    "",
    "test-file/test/event_test.js.html#lineNumber15",
    "libhoney events accepts dict-like arguments to .add()",
    "test"
  ],
  [
    "",
    "test-file/test/event_test.js.html#lineNumber39",
    "libhoney events converts all values to primitive types in .add/.addField",
    "test"
  ],
  [
    "",
    "test-file/test/event_test.js.html#lineNumber7",
    "libhoney events inherit fields and dyn_fields from builder",
    "test"
  ],
  [
    "",
    "test-file/test/event_test.js.html#lineNumber28",
    "libhoney events it toString()'s keys from Maps in .add()",
    "test"
  ],
  [
    "src/builder.js",
    "file/src/builder.js.html",
    "src/builder.js",
    "file"
  ],
  [
    "src/builder.js~builder#add",
    "class/src/builder.js~Builder.html#instance-method-add",
    "src/builder.js~Builder#add",
    "method"
  ],
  [
    "src/builder.js~builder#adddynamicfield",
    "class/src/builder.js~Builder.html#instance-method-addDynamicField",
    "src/builder.js~Builder#addDynamicField",
    "method"
  ],
  [
    "src/builder.js~builder#addfield",
    "class/src/builder.js~Builder.html#instance-method-addField",
    "src/builder.js~Builder#addField",
    "method"
  ],
  [
    "src/builder.js~builder#newbuilder",
    "class/src/builder.js~Builder.html#instance-method-newBuilder",
    "src/builder.js~Builder#newBuilder",
    "method"
  ],
  [
    "src/builder.js~builder#newevent",
    "class/src/builder.js~Builder.html#instance-method-newEvent",
    "src/builder.js~Builder#newEvent",
    "method"
  ],
  [
    "src/builder.js~builder#sendnow",
    "class/src/builder.js~Builder.html#instance-method-sendNow",
    "src/builder.js~Builder#sendNow",
    "method"
  ],
  [
    "src/event.js",
    "file/src/event.js.html",
    "src/event.js",
    "file"
  ],
  [
    "src/event.js~event#add",
    "class/src/event.js~Event.html#instance-method-add",
    "src/event.js~Event#add",
    "method"
  ],
  [
    "src/event.js~event#addfield",
    "class/src/event.js~Event.html#instance-method-addField",
    "src/event.js~Event#addField",
    "method"
  ],
  [
    "src/event.js~event#addmetadata",
    "class/src/event.js~Event.html#instance-method-addMetadata",
    "src/event.js~Event#addMetadata",
    "method"
  ],
  [
    "src/event.js~event#constructor",
    "class/src/event.js~Event.html#instance-constructor-constructor",
    "src/event.js~Event#constructor",
    "method"
  ],
  [
    "src/event.js~event#data",
    "class/src/event.js~Event.html#instance-member-data",
    "src/event.js~Event#data",
    "member"
  ],
  [
    "src/event.js~event#metadata",
    "class/src/event.js~Event.html#instance-member-metadata",
    "src/event.js~Event#metadata",
    "member"
  ],
  [
    "src/event.js~event#send",
    "class/src/event.js~Event.html#instance-method-send",
    "src/event.js~Event#send",
    "method"
  ],
  [
    "src/foreach.js",
    "file/src/foreach.js.html",
    "src/foreach.js",
    "file"
  ],
  [
    "src/libhoney.js",
    "file/src/libhoney.js.html",
    "src/libhoney.js",
    "file"
  ],
  [
    "src/libhoney.js~libhoney#add",
    "class/src/libhoney.js~Libhoney.html#instance-method-add",
    "src/libhoney.js~Libhoney#add",
    "method"
  ],
  [
    "src/libhoney.js~libhoney#adddynamicfield",
    "class/src/libhoney.js~Libhoney.html#instance-method-addDynamicField",
    "src/libhoney.js~Libhoney#addDynamicField",
    "method"
  ],
  [
    "src/libhoney.js~libhoney#addfield",
    "class/src/libhoney.js~Libhoney.html#instance-method-addField",
    "src/libhoney.js~Libhoney#addField",
    "method"
  ],
  [
    "src/libhoney.js~libhoney#constructor",
    "class/src/libhoney.js~Libhoney.html#instance-constructor-constructor",
    "src/libhoney.js~Libhoney#constructor",
    "method"
  ],
  [
    "src/libhoney.js~libhoney#newbuilder",
    "class/src/libhoney.js~Libhoney.html#instance-method-newBuilder",
    "src/libhoney.js~Libhoney#newBuilder",
    "method"
  ],
  [
    "src/libhoney.js~libhoney#newevent",
    "class/src/libhoney.js~Libhoney.html#instance-method-newEvent",
    "src/libhoney.js~Libhoney#newEvent",
    "method"
  ],
  [
    "src/libhoney.js~libhoney#sendnow",
    "class/src/libhoney.js~Libhoney.html#instance-method-sendNow",
    "src/libhoney.js~Libhoney#sendNow",
    "method"
  ],
  [
    "src/transmission.js",
    "file/src/transmission.js.html",
    "src/transmission.js",
    "file"
  ],
  [
    "test/builder_test.js",
    "test-file/test/builder_test.js.html",
    "test/builder_test.js",
    "testFile"
  ],
  [
    "test/event_test.js",
    "test-file/test/event_test.js.html",
    "test/event_test.js",
    "testFile"
  ],
  [
    "test/libhoney_test.js",
    "test-file/test/libhoney_test.js.html",
    "test/libhoney_test.js",
    "testFile"
  ],
  [
    "test/transmission_test.js",
    "test-file/test/transmission_test.js.html",
    "test/transmission_test.js",
    "testFile"
  ],
  [
    "",
    "test-file/test/transmission_test.js.html#lineNumber4",
    "transmission",
    "test"
  ],
  [
    "",
    "test-file/test/transmission_test.js.html#lineNumber6",
    "transmission should eventually send a single event (after the timeout)",
    "test"
  ]
]